# Generated by Django 4.2 on 2026-03-03 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='game',
            name='games_api_g_categor_079a0e_idx',
        ),
        migrations.RemoveField(
            model_name='game',
            name='category',
        ),
        migrations.AddField(
            model_name='game',
            name='categories',
            field=models.ManyToManyField(related_name='games', to='games_api.category'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['-created_at'], name='games_api_g_created_7dd361_idx'),
        ),
    ]
