# Generated by Django 4.2 on 2026-03-03 22:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games_api', '0002_remove_game_games_api_g_categor_079a0e_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='rating',
        ),
        migrations.CreateModel(
            name='UserRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('rating', models.IntegerField(help_text='Rating from 1 to 5 stars', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='games_api.game')),
            ],
            options={
                'verbose_name_plural': 'User Ratings',
                'unique_together': {('game', 'user_id')},
            },
        ),
    ]
