# Generated by Django 4.2 on 2026-03-04 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games_api', '0003_remove_game_rating_userrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard'), ('extreme', 'Extreme')], default='easy', max_length=20),
        ),
        migrations.AlterField(
            model_name='game',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='is new'),
        ),
    ]
