# Generated by Django 4.2 on 2026-03-04 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games_api', '0004_alter_game_difficulty_alter_game_is_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='difficulty',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard'), ('extreme', 'Extreme')], default='easy', max_length=20),
        ),
    ]
